# Site settings
title: SDSMT MCS clubs
email: mcs.sdsmt@gmail.com
description: This is the webpage for the various student organizations of the MCS department
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username: mcs-sdsmt

# Build settings
include: ['_pages']
permalink: /:title/

markdown: kramdown
syntax-highlighting:
    enabled : true
kramdown:
    input: GFM

gems:
    - jekyll-sitemap
